#!/bin/bash
source .env
export APP_NAME="explorer"
export PLATFORM_URL="localhost"
export PLATFORM_HOST='Host(`localhost`) || Host(`127.0.0.1`)' 
export PLATFORM_API_HOST='(Host(`localhost`) && PathPrefix(`/api/`)) || (Host(`127.0.0.1`) && PathPrefix(`/api/`))' 
export DEV_MODE=true
export APP_NAME=$APP_NAME
export BASE_URL=localhost
docker compose $@