version: '3'
services:    
  app-api:
    container_name: "${APP_NAME}-app-api"
    extends:
      file: docker-compose.yml
      service: app-api
    depends_on:
      - database
    environment:
      - APP_NAME=${APP_NAME}
      - PREVIEW=${PREVIEW}
      - POSTGRES_HOST=${APP_NAME}-database
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$APP_NAME-api.rule=Host(`${APP_NAME}.${BASE_URL}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.$APP_NAME-api.entrypoints=websecure"
      - "traefik.http.services.$APP_NAME-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=web"
      - "traefik.http.routers.$APP_NAME-api.tls=true"
      - "traefik.http.routers.$APP_NAME-api.tls.certresolver=le"
  
  database:
    container_name: "${APP_NAME}-database"
    extends:
      file: docker-compose.yml
      service: database
    networks:
      - internal

  app-ui:
    container_name: "${APP_NAME}-app-ui"
    build:
      context: ./app-ui
      # expose ./configs as additional context to enable copying-in of
      # the respective explorer.config.yml file during the Dockerfile build
      additional_contexts:
        configs: configs
      dockerfile: Dockerfile.prod
      args:
        - APP_NAME=${APP_NAME}
        - PREVIEW=${PREVIEW}
        - CONFIG_FILE_NAME=${CONFIG_FILE_NAME}
    depends_on:
      - app-api
    networks:
      - web
    environment:
      - APP_NAME=${APP_NAME}
      - PREVIEW=${PREVIEW}
      - KEYCLOAK_CLIENT_ID_SECRET=${KEYCLOAK_CLIENT_ID_SECRET}
    volumes:
      - ./configs/$CONFIG_FILE_NAME:/config/explorer.config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$APP_NAME-ui.rule=Host(`${APP_NAME}.${BASE_URL}`)"
      - "traefik.http.routers.$APP_NAME-ui.entrypoints=websecure"
      - "traefik.http.services.$APP_NAME-ui.loadbalancer.server.port=8000"
      - "traefik.http.routers.$APP_NAME-ui.tls.certresolver=le"
      - "traefik.http.routers.$APP_NAME-ui.tls=true"
      - "traefik.docker.network=web"

networks:
  local-keycloak:
  web:
    external: true
  internal:
    external: false
