FROM mcr.microsoft.com/playwright/python:v1.49.1-noble

RUN mkdir -p /tests
COPY ./requirements.txt /tests/requirements.txt
WORKDIR /tests
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["pytest", "--capture=tee-sys", "--tracing", "off"]
CMD ["--junit-xml=/tests/results/test-results-all.xml", "."]