FROM python:3.10

COPY ./requirements.txt /srv/app/requirements.txt
WORKDIR /srv/app

RUN pip install --no-cache-dir -r requirements.txt
COPY . /srv/app

CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]