FROM python:3.10

RUN mkdir -p /celery

WORKDIR /celery

COPY ./celery_config.py /celery/celery_config.py
COPY ./celery_tasks /celery/celery_tasks
COPY ./requirements.txt /celery/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["celery", "-A", "celery_config.celery_app", "worker", "--loglevel=info"]
