export function generateNewProjectName() {
    const names = [
        "cooking-bot-agent",
        "homework-assistant",
        "socks-sorter-agent",
        "toothpaste-squeezer-agent",
        "pillow-fluffer-agent",
        "quantum-sweeper-agent",
        "grape-peeler-agent",
        "laundry-meditator-agent",
        "burrito-folder-agent",
        "meme-curator-agent",
        "dust-whisperer-agent",
        "email-apologizer-agent",
        "cat-mind-reader-agent",
        "shower-singer-agent",
        "keyboard-tickler-agent",
        "deadline-dodger-agent",
        "banana-counselor-agent",
        "wifi-mystic-agent",
        "snack-dispenser-agent",
        "drama-detector-agent",
        "existential-crisis-coach-agent",
        "wormhole-librarian-agent",
        "teabag-orchestrator-agent",
        "emotion-scrambler-agent",
        "cloud-petter-agent",
        "bean-counter-confuser-agent",
        "sneeze-interpreter-agent",
        "parallel-dimension-tour-guide-agent",
        "boredom-igniter-agent",
        "left-sock-agent",
        "time-loop-negotiator-agent",
        "awkward-silence-filler-agent",
        "coffee-vibration-analyzer-agent",
        "quantum-toast-aligner-agent",
        "nap-strategist-agent",
        "algorithmic-daydreamer-agent",
        "reality-check-denier-agent",
        "laughter-echo-agent",
        "soup-whisperer-agent",
        "tinfoil-hat-designer-agent",
    ];
    // random 4 digit number
    const randomNumber = Math.floor(Math.random() * 10000);
    return names[Math.floor(Math.random() * names.length)] + "-" + randomNumber;
}