"""added creation date to traces and datasets

Revision ID: 0c72d9a0d0f1
Revises: 5a6bee133293
Create Date: 2024-08-25 13:26:42.037876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c72d9a0d0f1'
down_revision: Union[str, None] = '5a6bee133293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE datasets SET time_created = NOW()")
    op.execute("ALTER TABLE datasets ALTER COLUMN time_created SET NOT NULL")
    op.add_column('traces', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE traces SET time_created = NOW()")
    op.execute("ALTER TABLE traces ALTER COLUMN time_created SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'time_created')
    op.drop_column('datasets', 'time_created')
    # ### end Alembic commands ###
