"""switched extra_data type from string to JSON

Revision ID: 51a1f997a0f5
Revises: 9b83cef4c7b7
Create Date: 2024-08-31 21:26:37.666140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a1f997a0f5'
down_revision: Union[str, None] = '9b83cef4c7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE datasets ALTER COLUMN extra_metadata TYPE JSON USING extra_metadata::JSON")
    op.execute("ALTER TABLE traces ALTER COLUMN extra_metadata TYPE JSON USING extra_metadata::JSON")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traces', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('datasets', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
