"""added trace names

Revision ID: 5b89c5fb6059
Revises: 137113531aa2
Create Date: 2024-11-01 12:40:20.026605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b89c5fb6059'
down_revision: Union[str, None] = '137113531aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('traces', sa.Column('name', sa.String(), nullable=True))
    op.execute("UPDATE traces SET name = 'Run #' || index::text WHERE name IS NULL")
    op.execute('ALTER TABLE traces ALTER COLUMN name SET NOT NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'name')
    # ### end Alembic commands ###
