"""added annotation timestamp

Revision ID: 8cd93507c8f3
Revises: f232e65bbaa4
Create Date: 2024-08-14 23:09:24.122514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd93507c8f3'
down_revision: Union[str, None] = 'f232e65bbaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE annotations SET time_created = NOW() WHERE time_created IS NULL')
    op.execute('ALTER TABLE annotations ALTER COLUMN time_created SET NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'time_created')
    # ### end Alembic commands ###
