"""Add indices to the tables.

Revision ID: b8f0b197b931
Revises: d8abc01ed12f
Create Date: 2025-01-16 18:16:47.732775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f0b197b931'
down_revision: Union[str, None] = 'd8abc01ed12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_annotations_trace_id', 'annotations', ['trace_id'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('idx_datasets_user_id', 'datasets', ['user_id'], unique=False)
    op.create_index('idx_traces_dataset_id', 'traces', ['dataset_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_traces_dataset_id', table_name='traces')
    op.drop_index('idx_datasets_user_id', table_name='datasets')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_annotations_trace_id', table_name='annotations')
    # ### end Alembic commands ###
