"""added creation date to link sharing

Revision ID: e44c2a92c154
Revises: 0c72d9a0d0f1
Create Date: 2024-08-25 14:21:59.725140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44c2a92c154'
down_revision: Union[str, None] = '0c72d9a0d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_links', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE shared_links SET time_created = NOW()")
    op.execute("ALTER TABLE shared_links ALTER COLUMN time_created SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_links', 'time_created')
    # ### end Alembic commands ###
