"""added user table for user display information

Revision ID: f232e65bbaa4
Revises: b7c27b731345
Create Date: 2024-08-14 16:37:11.001327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f232e65bbaa4'
down_revision: Union[str, None] = 'b7c27b731345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('image_url_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Manually replaced the following command
    # op.alter_column('annotations', 'user_id',
    #           existing_type=sa.VARCHAR(),
    #           type_=sa.UUID(),
    #           existing_nullable=False)
    op.execute('ALTER TABLE annotations ALTER COLUMN user_id TYPE UUID USING user_id::uuid')
    op.create_foreign_key(None, 'annotations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.alter_column('annotations', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
