name: Trigger Internal Builds

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Explorer CI"]
    types:
      - completed
    branches:
      - main
      - prod

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check if manually triggered or via workflow_run
        # this step determines if the workflow was triggered manually or via another workflow. It then sets REF to either the name of the previous workflow run or the current branch name
        run: |
          if [ -n "${{ github.event.inputs.ref }}" ]; then
            echo "Setting REF to ${{ github.event.inputs.ref }}"
            echo "::set-env name=REF::${{ github.event.inputs.ref }}"
          else
            echo "Setting REF to ${{ github.ref }}"
            echo "::set-env name=REF::${{ github.ref }}"
          fi
      - name: trigger production build
        # only on production branch
        if: env.REF == 'refs/heads/prod'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-prod-images.yaml/dispatches \
          -d '{"ref":"main"}'
      - name: trigger pre-production build
        # only on 'main' branch
        if: env.REF == 'refs/heads/main'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-latest-images.yaml/dispatches \
          -d '{"ref":"main"}'
