name: Trigger Internal Builds

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Explorer CI"]
    types:
      - completed
    branches:
      - main
      - prod

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check if manually triggered or via workflow_run
        run: |
          REF="${{ github.event.inputs.ref || github.ref }}"
          echo "REF=$REF" >> $GITHUB_ENV

      - name: trigger production build
        if: env.REF == 'refs/heads/prod'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-prod-images.yaml/dispatches \
          -d '{"ref":"main"}'

      - name: trigger pre-production build
        if: env.REF == 'refs/heads/main'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-latest-images.yaml/dispatches \
          -d '{"ref":"main"}'
