name: Trigger Internal Builds

on:
  push:
    branches:
      - main
      - prod
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: trigger production build
        # only on production branch
        if: github.ref == 'refs/heads/prod'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-prod-images.yaml/dispatches \
          -d '{"ref":"main"}'
      - name: trigger pre-production build
        # only on 'main' branch
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PROD_REPO_PAT }}" \
          https://api.github.com/repos/invariantlabs-ai/explorer-prod/actions/workflows/build-latest-images.yaml/dispatches \
          -d '{"ref":"main"}'
